version: '3.8'
services:
  gamepad-server:
    build: 
      context: .
      network: host
    ports:
      - "80:8000" # Zmiana portu na 80, aby obsługiwać czysty adres http://gamepad
    devices:
      - "/dev/uinput:/dev/uinput"
    restart: unless-stopped